-- Run in Snowsight as ACCOUNTADMIN. One-time setup.
USE ROLE ACCOUNTADMIN;

CREATE WAREHOUSE IF NOT EXISTS COPILOT_WH
  WAREHOUSE_SIZE = XSMALL AUTO_SUSPEND = 60 AUTO_RESUME = TRUE INITIALLY_SUSPENDED = TRUE;

-- Cap runaway LLM-generated queries. Without this the account default applies
-- (172800s = 48h): the app gives up on a query after 60s and the repair loop
-- immediately launches another, while the abandoned one keeps burning credits for
-- up to two days. 60s matches the client-side timeout in backend mcp_client._run.
-- Safe to re-run (SET is idempotent).
ALTER WAREHOUSE COPILOT_WH SET STATEMENT_TIMEOUT_IN_SECONDS = 60;

CREATE DATABASE IF NOT EXISTS MEDTECH_ANALYTICS;
CREATE SCHEMA IF NOT EXISTS MEDTECH_ANALYTICS.BRONZE;
CREATE SCHEMA IF NOT EXISTS MEDTECH_ANALYTICS.SILVER;
CREATE SCHEMA IF NOT EXISTS MEDTECH_ANALYTICS.GOLD;
CREATE SCHEMA IF NOT EXISTS MEDTECH_ANALYTICS.COPILOT;

CREATE ROLE IF NOT EXISTS COPILOT_ADMIN;    -- build + unmasked read
CREATE ROLE IF NOT EXISTS COPILOT_APP_RO;   -- copilot runtime reads
CREATE ROLE IF NOT EXISTS COPILOT_APP_WRITER; -- feedback/log/eval writes
GRANT ROLE COPILOT_APP_RO TO ROLE COPILOT_ADMIN;
GRANT ROLE COPILOT_APP_WRITER TO ROLE COPILOT_ADMIN;
GRANT ROLE COPILOT_ADMIN TO ROLE SYSADMIN;

GRANT USAGE ON WAREHOUSE COPILOT_WH TO ROLE COPILOT_APP_RO;
GRANT USAGE ON WAREHOUSE COPILOT_WH TO ROLE COPILOT_APP_WRITER;
GRANT USAGE ON WAREHOUSE COPILOT_WH TO ROLE COPILOT_ADMIN;
GRANT ALL ON DATABASE MEDTECH_ANALYTICS TO ROLE COPILOT_ADMIN;
GRANT ALL ON ALL SCHEMAS IN DATABASE MEDTECH_ANALYTICS TO ROLE COPILOT_ADMIN;

-- Read-only surface for the app: all of GOLD, plus exactly two COPILOT tables
GRANT USAGE ON DATABASE MEDTECH_ANALYTICS TO ROLE COPILOT_APP_RO;
GRANT USAGE ON SCHEMA MEDTECH_ANALYTICS.GOLD TO ROLE COPILOT_APP_RO;
GRANT USAGE ON SCHEMA MEDTECH_ANALYTICS.COPILOT TO ROLE COPILOT_APP_RO;
GRANT SELECT ON ALL TABLES IN SCHEMA MEDTECH_ANALYTICS.GOLD TO ROLE COPILOT_APP_RO;
GRANT SELECT ON FUTURE TABLES IN SCHEMA MEDTECH_ANALYTICS.GOLD TO ROLE COPILOT_APP_RO;
GRANT SELECT ON ALL VIEWS IN SCHEMA MEDTECH_ANALYTICS.GOLD TO ROLE COPILOT_APP_RO;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA MEDTECH_ANALYTICS.GOLD TO ROLE COPILOT_APP_RO;

-- The COPILOT schema holds BOTH the AI data library the app reads (SCHEMA_CARDS,
-- GLOSSARY) and the operational tables it writes (REQUEST_LOG = every user's raw
-- question + generated SQL + role, FEEDBACK = free-text comments, EVAL_RESULTS).
-- A schema-wide `SELECT ON ALL/FUTURE TABLES` grant here therefore let COPILOT_APP_RO
-- -- i.e. every analyst -- read every other user's logged questions and comments.
-- Layer 3 must not depend on layer 1's schema allowlist to close that, so the grant
-- is per-table on the two tables the app actually reads. The REVOKEs undo the old
-- schema-wide grants on an account bootstrapped before this change; they are no-ops
-- on a fresh account.
REVOKE SELECT ON ALL TABLES IN SCHEMA MEDTECH_ANALYTICS.COPILOT FROM ROLE COPILOT_APP_RO;
REVOKE SELECT ON FUTURE TABLES IN SCHEMA MEDTECH_ANALYTICS.COPILOT FROM ROLE COPILOT_APP_RO;

-- Created here (empty) so the per-table grants below can be issued on a fresh
-- account before `make ai-library` populates them. Column lists must stay in sync
-- with warehouse/load_ai_library.py, which re-creates these tables WITH COPY GRANTS
-- so re-loading the library does not silently drop the grants.
CREATE TABLE IF NOT EXISTS MEDTECH_ANALYTICS.COPILOT.GLOSSARY (
  term VARCHAR, definition VARCHAR, related_tables VARCHAR, embedding VECTOR(FLOAT, 768)
);
CREATE TABLE IF NOT EXISTS MEDTECH_ANALYTICS.COPILOT.SCHEMA_CARDS (
  table_name VARCHAR, card VARCHAR, embedding VECTOR(FLOAT, 768)
);
GRANT SELECT ON TABLE MEDTECH_ANALYTICS.COPILOT.SCHEMA_CARDS TO ROLE COPILOT_APP_RO;
GRANT SELECT ON TABLE MEDTECH_ANALYTICS.COPILOT.GLOSSARY TO ROLE COPILOT_APP_RO;

-- Writer: append-only operational tables
GRANT USAGE ON DATABASE MEDTECH_ANALYTICS TO ROLE COPILOT_APP_WRITER;
GRANT USAGE ON SCHEMA MEDTECH_ANALYTICS.COPILOT TO ROLE COPILOT_APP_WRITER;

-- Operational tables (exist before dbt so grants above cover them)
CREATE TABLE IF NOT EXISTS MEDTECH_ANALYTICS.COPILOT.FEEDBACK (
  feedback_id VARCHAR DEFAULT UUID_STRING(), conversation_id VARCHAR, request_id VARCHAR,
  rating VARCHAR, comment VARCHAR, prompt_version VARCHAR, created_at TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
CREATE TABLE IF NOT EXISTS MEDTECH_ANALYTICS.COPILOT.REQUEST_LOG (
  request_id VARCHAR, conversation_id VARCHAR, user_role VARCHAR, question VARCHAR,
  intent VARCHAR, sql_text VARCHAR, status VARCHAR, error_type VARCHAR,
  e2e_ms NUMBER, retrieval_ms NUMBER, tokens_in NUMBER, tokens_out NUMBER,
  prompt_version VARCHAR, created_at TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
CREATE TABLE IF NOT EXISTS MEDTECH_ANALYTICS.COPILOT.EVAL_RESULTS (
  run_id VARCHAR, case_id VARCHAR, kind VARCHAR, passed BOOLEAN, score FLOAT,
  detail VARCHAR, git_sha VARCHAR, prompt_version VARCHAR, created_at TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
GRANT INSERT ON TABLE MEDTECH_ANALYTICS.COPILOT.FEEDBACK TO ROLE COPILOT_APP_WRITER;
GRANT INSERT ON TABLE MEDTECH_ANALYTICS.COPILOT.REQUEST_LOG TO ROLE COPILOT_APP_WRITER;
GRANT INSERT ON TABLE MEDTECH_ANALYTICS.COPILOT.EVAL_RESULTS TO ROLE COPILOT_APP_WRITER;

-- Admin reads the ops tables directly (Admin Console, eval harness). This grant has to
-- be explicit: COPILOT_ADMIN inherits COPILOT_APP_RO, and it used to reach these tables
-- only through that inheritance -- so revoking the analyst's schema-wide SELECT above
-- silently took admin's monitoring access with it. A monitoring role should not depend
-- on what the least-privileged role happens to be allowed to read.
GRANT SELECT ON ALL TABLES IN SCHEMA MEDTECH_ANALYTICS.COPILOT TO ROLE COPILOT_ADMIN;
GRANT SELECT ON FUTURE TABLES IN SCHEMA MEDTECH_ANALYTICS.COPILOT TO ROLE COPILOT_ADMIN;

-- Service user: key-pair auth only (no password), TYPE=SERVICE avoids MFA policy
CREATE USER IF NOT EXISTS COPILOT_SVC
  TYPE = SERVICE
  DEFAULT_ROLE = COPILOT_ADMIN
  DEFAULT_WAREHOUSE = COPILOT_WH
  RSA_PUBLIC_KEY = 'PASTE_OUTPUT_OF_gen_keypair_HERE';
GRANT ROLE COPILOT_ADMIN TO USER COPILOT_SVC;
GRANT ROLE COPILOT_APP_RO TO USER COPILOT_SVC;
GRANT ROLE COPILOT_APP_WRITER TO USER COPILOT_SVC;

-- Prevent secondary-role privilege stacking on the service user (see governance.sql)
ALTER USER COPILOT_SVC SET DEFAULT_SECONDARY_ROLES = ();

-- Bronze landing: internal stage + CSV format
CREATE FILE FORMAT IF NOT EXISTS MEDTECH_ANALYTICS.BRONZE.CSV_FMT
  TYPE = CSV SKIP_HEADER = 1 FIELD_OPTIONALLY_ENCLOSED_BY = '"' EMPTY_FIELD_AS_NULL = TRUE;
CREATE STAGE IF NOT EXISTS MEDTECH_ANALYTICS.BRONZE.SEED_STAGE
  FILE_FORMAT = (FORMAT_NAME = 'MEDTECH_ANALYTICS.BRONZE.CSV_FMT');
